var D1 = document.getElementById("D1");
var D2 = document.getElementById("D2");
var D3 = document.getElementById("D3");
var D4 = document.getElementById("D4");
var D5 = document.getElementById("D5");
var D6 = document.getElementById("D6");
var d1 = document.getElementById("d1");
var d2 = document.getElementById("d2");
var d3 = document.getElementById("d3");
var d4 = document.getElementById("d4");
var d5 = document.getElementById("d5");
var d6 = document.getElementById("d6");
d1.style.display = "block";
d2.style.display = "none";
d3.style.display = "none";
d4.style.display = "none";
d5.style.display = "none";
d6.style.display = "none";
D1.onclick = function () {
    d1.style.display = "block";
    d2.style.display = "none";
    d3.style.display = "none";
    d4.style.display = "none";
    d5.style.display = "none";
    d6.style.display = "none";
    D1.style.filter = "grayscale(20%)";
    D2.style.filter = "grayscale(100%)";
    D3.style.filter = "grayscale(100%)";
    D4.style.filter = "grayscale(100%)";
    D5.style.filter = "grayscale(100%)";
    D6.style.filter = "grayscale(100%)";
}
D2.onclick = function () {
    d1.style.display = "none";
    d2.style.display = "block";
    d3.style.display = "none";
    d4.style.display = "none";
    d5.style.display = "none";
    d6.style.display = "none";
    D2.style.filter = "grayscale(20%)";
    D1.style.filter = "grayscale(100%)";
    D3.style.filter = "grayscale(100%)";
    D4.style.filter = "grayscale(100%)";
    D5.style.filter = "grayscale(100%)";
    D6.style.filter = "grayscale(100%)";
}
D3.onclick = function () {
    d1.style.display = "none";
    d3.style.display = "block";
    d2.style.display = "none";
    d4.style.display = "none";
    d5.style.display = "none";
    d6.style.display = "none";
    D3.style.filter = "grayscale(20%)";
    D2.style.filter = "grayscale(100%)";
    D1.style.filter = "grayscale(100%)";
    D4.style.filter = "grayscale(100%)";
    D5.style.filter = "grayscale(100%)";
    D6.style.filter = "grayscale(100%)";
}
D4.onclick = function () {
    d1.style.display = "none";
    d4.style.display = "block";
    d3.style.display = "none";
    d2.style.display = "none";
    d5.style.display = "none";
    d6.style.display = "none";
    D4.style.filter = "grayscale(20%)";
    D2.style.filter = "grayscale(100%)";
    D3.style.filter = "grayscale(100%)";
    D1.style.filter = "grayscale(100%)";
    D5.style.filter = "grayscale(100%)";
    D6.style.filter = "grayscale(100%)";
}
D5.onclick = function () {
    d1.style.display = "none";
    d5.style.display = "block";
    d3.style.display = "none";
    d4.style.display = "none";
    d2.style.display = "none";
    d6.style.display = "none";
    D5.style.filter = "grayscale(20%)";
    D2.style.filter = "grayscale(100%)";
    D3.style.filter = "grayscale(100%)";
    D4.style.filter = "grayscale(100%)";
    D1.style.filter = "grayscale(100%)";
    D6.style.filter = "grayscale(100%)";
}
D6.onclick = function () {
    d1.style.display = "none";
    d6.style.display = "block";
    d3.style.display = "none";
    d4.style.display = "none";
    d5.style.display = "none";
    d2.style.display = "none";
    D6.style.filter = "grayscale(20%)";
    D2.style.filter = "grayscale(100%)";
    D3.style.filter = "grayscale(100%)";
    D4.style.filter = "grayscale(100%)";
    D5.style.filter = "grayscale(100%)";
    D1.style.filter = "grayscale(100%)";
}


